/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-09-23 10:58:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bangcuuchuong_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


  public int sum(int a, int b) {
      return a * b;
  }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"./css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"tittle\"><h1 style=\"text-align: center;\"> Bảng cửu chương</h1></div>\r\n");
      out.write("\t\t<form action=\"\">\r\n");
      out.write("\t\t<input type=\"text\" name=\"num\" value=\"\" placeholder=\"Nhập số Bảng cửu chương\">\r\n");
      out.write("\t\t<input type=\"submit\"  value=\"Xem\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t");

			String cc=request.getParameter("num");
			if(cc!=null){
      out.write("\r\n");
      out.write("\t\t\t\t<p> bảng cửu chương</p>\r\n");
      out.write("\t\t\t\t<div class=\"cuuchuong\">\r\n");
      out.write("\t\t\t\t\t<table border=\"1\"  cellpadding=\"0\" cellspacing=\"1\"\r\n");
      out.write("    \t\t\twidth=\"100\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Nhân ");
      out.print(cc );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t");
for(int i=1;i<=10;i++){
					 		int c=Integer.parseInt(cc);
      out.write(" \r\n");
      out.write("\t\t\t\t\t      <tr>\r\n");
      out.write("\t\t\t\t\t          <td> <p> ");
      out.print(cc );
      out.write(' ');
      out.write('X');
      out.write(' ');
      out.print(i );
      out.write(' ');
      out.write('=');
      out.write(' ');
      out.print(sum(c,i) );
      out.write("</p> </td>\r\n");
      out.write("\t\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t\t      ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 
				}
		
      out.write("\r\n");
      out.write("\t\t<!-- \r\n");
      out.write("\t\t<div class=\"cuuchuong\">\r\n");
      out.write("\t\t<table border=\"1\"  cellpadding=\"0\" cellspacing=\"1\"\r\n");
      out.write("    \t\t\twidth=\"100\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Nhân 1</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t");
for(int i=1;i<=10;i++){ 
      out.write(" \r\n");
      out.write("\t\t\t\t\t      <tr>\r\n");
      out.write("\t\t\t\t\t          <td> <p> 1 X ");
      out.print(i );
      out.write(' ');
      out.write('=');
      out.write(' ');
      out.print(sum(1,i) );
      out.write("</p> </td>\r\n");
      out.write("\t\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t\t      ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<table border=\"1\"  cellpadding=\"0\" cellspacing=\"1\"\r\n");
      out.write("    \t\t\twidth=\"100\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Nhân 2</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t");
for(int i=1;i<=10;i++){ 
      out.write(" \r\n");
      out.write("\t\t\t\t\t      <tr>\r\n");
      out.write("\t\t\t\t\t          <td> <p> 2 X ");
      out.print(i );
      out.write(' ');
      out.write('=');
      out.write(' ');
      out.print(sum(2,i) );
      out.write("</p> </td>\r\n");
      out.write("\t\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t\t      ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table border=\"1\"  cellpadding=\"0\" cellspacing=\"1\"\r\n");
      out.write("    \t\t\twidth=\"100\" style=\"float: left;\" >\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Nhân 3</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t");
for(int i=1;i<=10;i++){ 
      out.write(" \r\n");
      out.write("\t\t\t\t\t      <tr>\r\n");
      out.write("\t\t\t\t\t          <td> <p> 3 X ");
      out.print(i );
      out.write(' ');
      out.write('=');
      out.write(' ');
      out.print(sum(3,i) );
      out.write("</p> </td>\r\n");
      out.write("\t\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t\t      ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<table border=\"1\"  cellpadding=\"0\" cellspacing=\"1\"\r\n");
      out.write("    \t\t\twidth=\"100\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Nhân 4</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t");
for(int i=1;i<=10;i++){ 
      out.write(" \r\n");
      out.write("\t\t\t\t\t      <tr>\r\n");
      out.write("\t\t\t\t\t          <td> <p> 4 X ");
      out.print(i );
      out.write(' ');
      out.write('=');
      out.write(' ');
      out.print(sum(4,i) );
      out.write("</p> </td>\r\n");
      out.write("\t\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t\t      ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table border=\"1\"  cellpadding=\"0\" cellspacing=\"1\"\r\n");
      out.write("    \t\t\twidth=\"100\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Nhân 5</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t");
for(int i=1;i<=10;i++){ 
      out.write(" \r\n");
      out.write("\t\t\t\t\t      <tr>\r\n");
      out.write("\t\t\t\t\t          <td> <p> 5 X ");
      out.print(i );
      out.write(' ');
      out.write('=');
      out.write(' ');
      out.print(sum(5,i) );
      out.write("</p> </td>\r\n");
      out.write("\t\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t\t      ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table border=\"1\"  cellpadding=\"0\" cellspacing=\"1\"\r\n");
      out.write("    \t\t\twidth=\"100\" style=\"float: left;\" >\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Nhân 6</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t");
for(int i=1;i<=10;i++){ 
      out.write(" \r\n");
      out.write("\t\t\t\t\t      <tr>\r\n");
      out.write("\t\t\t\t\t          <td> <p> 6 X ");
      out.print(i );
      out.write(' ');
      out.write('=');
      out.write(' ');
      out.print(sum(6,i) );
      out.write("</p> </td>\r\n");
      out.write("\t\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t\t      ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<table border=\"1\"  cellpadding=\"0\" cellspacing=\"1\"\r\n");
      out.write("    \t\t\twidth=\"100\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Nhân 7</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t");
for(int i=1;i<=10;i++){ 
      out.write(" \r\n");
      out.write("\t\t\t\t\t      <tr>\r\n");
      out.write("\t\t\t\t\t          <td> <p> 7 X ");
      out.print(i );
      out.write(' ');
      out.write('=');
      out.write(' ');
      out.print(sum(7,i) );
      out.write("</p> </td>\r\n");
      out.write("\t\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t\t      ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table border=\"1\"  cellpadding=\"0\" cellspacing=\"1\"\r\n");
      out.write("    \t\t\twidth=\"100\" style=\"float: left;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Nhân 8</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t");
for(int i=1;i<=10;i++){ 
      out.write(" \r\n");
      out.write("\t\t\t\t\t      <tr>\r\n");
      out.write("\t\t\t\t\t          <td> <p> 8 X ");
      out.print(i );
      out.write(' ');
      out.write('=');
      out.write(' ');
      out.print(sum(8,i) );
      out.write("</p> </td>\r\n");
      out.write("\t\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t\t      ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<table border=\"1\"  cellpadding=\"0\" cellspacing=\"1\"\r\n");
      out.write("    \t\t\twidth=\"100\" style=\"float: left;\" >\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Nhân 9</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t \t");
for(int i=1;i<=10;i++){ 
      out.write(" \r\n");
      out.write("\t\t\t\t\t      <tr>\r\n");
      out.write("\t\t\t\t\t          <td> <p> 9 X ");
      out.print(i );
      out.write(' ');
      out.write('=');
      out.write(' ');
      out.print(sum(9,i) );
      out.write("</p> </td>\r\n");
      out.write("\t\t\t\t\t      </tr>\r\n");
      out.write("\t\t\t\t\t      ");
} 
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div> -->\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
