/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-09-22 13:18:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Trường Đẹp Trai</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/mail.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t <div class=\"gmail\" id=\"gmail\">\r\n");
      out.write("   <div class=\"tittle\"> \r\n");
      out.write("    \r\n");
      out.write("     <div class=\"control\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li style=\"width: 82%;\"><div class=\"left\"><h2>Thư Mới </h2></div></li>\r\n");
      out.write("        <li><a href=\"#\" onclick=\"zoomin()\"><h2 id=\"zoom\">_</h2></a></li>\r\n");
      out.write("        <li><a href=\"#\" onclick=\"fullscreen()\" ><h2 id=\"fullscreen\"> <img src=\"https://ssl.gstatic.com/ui/v1/icons/mail/expand_window.png\"></h2></a></li>\r\n");
      out.write("        <li><a href=\"#\" onclick=\"closee()\"><h2 style=\"margin-top: 18px;\">X</h2></a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("   </div>\r\n");
      out.write("   </div>\r\n");
      out.write("  \r\n");
      out.write("   <div class=\"connten\" id=\"connten\" style=\"display: block;\">\r\n");
      out.write("     <div class=\"nguoinhan\"><span id=\"to\">Người Nhận</span>\r\n");
      out.write("      <input type=\"text\" name=\"a\"  spellcheck=\"true\" style=\"border: none;margin-top: 5px;\" onclick=\"haha() \">\r\n");
      out.write("  \r\n");
      out.write("      <hr>\r\n");
      out.write("   \r\n");
      out.write("      <input class=\"txt_to\" type=\"text\" name=\"a\" placeholder=\"Chủ đề\" aria-label=\"Chủ đề\" tabindex=\"1\" spellcheck=\"true\" style=\"border: none;margin-left: 10px;\"onclick=\"hihi()\" >\r\n");
      out.write("      <hr>\r\n");
      out.write("         <script type=\"text/javascript\">\r\n");
      out.write("        function haha() {\r\n");
      out.write("          document.getElementById(\"to\").innerHTML = \"Đến\";\r\n");
      out.write("        }\r\n");
      out.write("         function hihi() {\r\n");
      out.write("          document.getElementById(\"to\").innerHTML = \"Người Nhận\";\r\n");
      out.write("        }\r\n");
      out.write("      </script>\r\n");
      out.write("      <textarea style=\"border: none;margin-left: 10px;\"></textarea>\r\n");
      out.write("      <div class=\"btn\">\r\n");
      out.write("           <button  type=\"button\" class=\"sent\" > Gửi</button>\r\n");
      out.write("           <button  type=\"button\" class=\"select\" > <img src=\"https://friconix.com/png/fi-xtldxx-sort-up-thin.png\" width=\"30\" height=\"20\"></button>\r\n");
      out.write("          \r\n");
      out.write("                  <ul style=\"display: flex;\r\n");
      out.write("    float: right;position: relative;right: 20%;\">\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"https://www.gstatic.com/images/icons/material/system/1x/text_format_black_20dp.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"https://www.gstatic.com/images/icons/material/system/1x/attach_file_black_20dp.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"https://www.gstatic.com/images/icons/material/system/1x/insert_link_black_20dp.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"https://www.gstatic.com/images/icons/material/system/1x/insert_emoticon_black_20dp.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"https://www.gstatic.com/images/icons/material/system/1x/attach_drive_black_20dp.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"https://www.gstatic.com/images/icons/material/system/1x/insert_photo_black_20dp.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"https://www.gstatic.com/images/icons/material/system/1x/lock_clock_black_20dp.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"https://www.gstatic.com/images/icons/material/system/1x/ink_pen_black_20dp.png\"></a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  <ul style=\"display: flex;\r\n");
      out.write("    float: right;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 0px;\r\n");
      out.write("    bottom: 0px;\">\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"https://www.gstatic.com/images/icons/material/system/1x/more_vert_black_20dp.png\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"https://www.gstatic.com/images/icons/material/system/1x/delete_black_20dp.png\"></a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("          \r\n");
      out.write("      </div>\r\n");
      out.write("     \r\n");
      out.write("     </div>\r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write(" <script>\r\n");
      out.write("function zoomin() {\r\n");
      out.write("  var x = document.getElementById('connten');\r\n");
      out.write("  var y = document.getElementById('gmail');\r\n");
      out.write("  if (x.style.display === 'none') {\r\n");
      out.write("    x.style.display = 'block';\r\n");
      out.write("    document.getElementById(\"zoom\").innerHTML = \"_\";\r\n");
      out.write("    y.style.width=\"42%\";\r\n");
      out.write("    y.style.right =\"2%\";\r\n");
      out.write("    y.style.bottom = \"0px\";\r\n");
      out.write("  } else {\r\n");
      out.write("    x.style.display = 'none';\r\n");
      out.write("    document.getElementById(\"zoom\").innerHTML = \"-\";\r\n");
      out.write("    y.style.width=\"42%\";\r\n");
      out.write("    y.style.right =\"2%\";\r\n");
      out.write("    y.style.bottom = \"0px\";\r\n");
      out.write("    document.getElementById(\"fullscreen\").className = \"full\";\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fullscreen() {\r\n");
      out.write("  var x = document.getElementById('connten');\r\n");
      out.write("  var y = document.getElementById('gmail');\r\n");
      out.write("  if(y.style.width===\"1000px\"){\r\n");
      out.write("    y.style.width=\"42%\";\r\n");
      out.write("    y.style.right =\"2%\";\r\n");
      out.write("    y.style.bottom = \"0px\";\r\n");
      out.write("    document.getElementById(\"fullscreen\").className = \"full\";\r\n");
      out.write("    document.getElementById(\"zoom\").innerHTML = \"_\";\r\n");
      out.write("    x.style.display = 'block';\r\n");
      out.write("  }\r\n");
      out.write("  else{\r\n");
      out.write("    y.style.width=\"1000px\";\r\n");
      out.write("    document.getElementById(\"zoom\").innerHTML = \"_\";\r\n");
      out.write("    document.getElementById(\"fullscreen\").className = \"exitfull\";\r\n");
      out.write("    x.style.display = 'block';\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closee() {\r\n");
      out.write("  document.getElementById('gmail').style.display = 'none';\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
