/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-27 16:45:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Random;
import bo.Giohangbo;
import bean.loaibean;
import bo.loaibo;
import bean.sachbean;
import java.util.ArrayList;
import bo.sachbo;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1606495035311L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bo.loaibo");
    _jspx_imports_classes.add("bo.Giohangbo");
    _jspx_imports_classes.add("bean.loaibean");
    _jspx_imports_classes.add("bo.sachbo");
    _jspx_imports_classes.add("java.util.Random");
    _jspx_imports_classes.add("bean.sachbean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("      <title>MinhKhai Búc</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <!-- Import Boostrap css, js, font awesome here -->   \r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap JS -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">    \r\n");
      out.write("    <link href=\"./css/home1.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/script.js\"></script>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write(" <link href=\"https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/home3.css\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"css/minhkhai_style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/login.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

response.setCharacterEncoding("utf-8");
	ArrayList<loaibean> dsloai=(ArrayList<loaibean>)request.getAttribute("dsloai");
	ArrayList<sachbean> ds=(ArrayList<sachbean>)request.getAttribute("dssach");
	int m=dsloai.size();
	int n=ds.size();
	 long soluong=0;
     if (session.getAttribute("GioHang")!=null){
     	Giohangbo gh=(Giohangbo)session.getAttribute("GioHang");
     	soluong=gh.Sum_cart();
     }
	Random rd=new Random();
	

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<div class=\"header-blue fixed-top\">\r\n");
      out.write("            <nav class=\"navbar navbar-dark navbar-expand-md navigation-clean-search\">\r\n");
      out.write("                <div class=\"container-fluid\"><a class=\"navbar-brand\" href=\"#\">MinhKhaiBook</a><button class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navcol-1\"><span class=\"sr-only\">Toggle navigation</span><span class=\"navbar-toggler-icon\"></span></button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navcol-1\">\r\n");
      out.write("                        <ul class=\"nav navbar-nav\">\r\n");
      out.write("                            <li class=\"nav-item\" role=\"presentation\"><a class=\"nav-link active\" href=\"SachController\">Trang Chủ</a></li> \r\n");
      out.write("                        </ul>\r\n");
      out.write("                          <div class=\"search_book\">\r\n");
      out.write("                            <form action=\"\">\r\n");
      out.write("                              <input class=\"form-control \" id=\"searchbook\" placeholder=\"Tìm sách\" name=\"txttk\" >\r\n");
      out.write("                            \r\n");
      out.write("                            </form>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        ");
 
                        	if(session.getAttribute("username")!=null){
                        	
                        		
      out.write("\r\n");
      out.write("                        \t\t\r\n");
      out.write("                        \t\t<div class=\"dropdown \">\r\n");
      out.write("                        \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <button class=\"dropbtn\"><i class=\"fas fa-user user_icon\"></i>Xin Chào ");
      out.print(session.getAttribute("username") );
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <a href=\"profileController\">Profile</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <a href=\"#\">Đơn hàng</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <a href=\"dangxuatController\">Log Out</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <a class=\"nav-link active\" href=\"lichsuMHController\">Lịch sử mua hàng</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                        \t");
 }else{
                        		
      out.write("\r\n");
      out.write("                        \t\t<form class=\"form-inline mr-auto\" target=\"_self\">\r\n");
      out.write("                            <!-- <div class=\"form-group\"><label for=\"search-field\"><i class=\"fa fa-search\"></i></label><input class=\"form-control search-field\" type=\"search\" name=\"search\" id=\"search-field\"></div> -->\r\n");
      out.write("                        </form><span class=\"navbar-text\"> <a id=\"f-login\" href=\"#\"  class=\"login\">Log In</a></span><a class=\"btn btn-light action-button\" id=\"f-signup\" role=\"button\" href=\"#\">Sign Up</a></div>\r\n");
      out.write("                        \r\n");
      out.write("                       ");
  	}
                       			
                        
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("           \r\n");
      out.write("        </div>");
      out.write("\r\n");
      out.write(" <div class=\"wrapper\">\r\n");
      out.write("        <!-- Sidebar Holder -->\r\n");
      out.write("        <nav id=\"sidebar\">\r\n");
      out.write("            <div class=\"sidebar-header\">\r\n");
      out.write("                <h3><a href=\"#\" id=\"mainlogo\">MinhKhai Búc</a></h3>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"list-unstyled components\">\r\n");
      out.write("                <p>Bảng điều khiển</p>\r\n");
      out.write("                <li  class=\"active\"> <a href=\"hahaha.jsp\" >Trang Chủ</a></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#homeSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\" class=\"dropdown-toggle\">Danh Mục Sách <span class=\"badge badge-pill badge-danger\"style=\"margin-left: 10px;\">Hot</span></a>\r\n");
      out.write("                    <ul class=\"collapse list-unstyled\" id=\"homeSubmenu\">\r\n");
      out.write("                        ");
 for(int i=0;i<m;i++){  
      out.write("\r\n");
      out.write("\t\t\t\t\t <li>\r\n");
      out.write("\t\t\t\t\t    <a href=\"SachController?type=");
      out.print(dsloai.get(i).getMaloai());
      out.write('"');
      out.write('>');
      out.print(dsloai.get(i).getTenloai() );
      out.write("<span class=\"badge badge-pill badge-danger\" style=\"margin-left: 10px;\">");
      out.print(rd.nextInt(100));
      out.write("</span></a>\r\n");
      out.write("\t\t\t\t\t  </li>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  ");
} 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"index.php?type=Clone-VN\">Văn phòng phẩm<span class=\"badge badge-pill badge-success\"style=\"margin-left: 10px;\">100</span></a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"index.php?type=Clone-US\">Đồ chơi- Thú bông <span class=\"badge badge-pill badge-success\"style=\"margin-left: 10px;\">150 </span></a></li>\r\n");
      out.write("              \t <li>\r\n");
      out.write("               \t\t<a href=\"index.php?type=Clone-EU\">Hàng lưu niệm <span class=\"badge badge-pill badge-success\" style=\"margin-left: 10px;\">134</span>\r\n");
      out.write("              \t\t </a>\r\n");
      out.write("               </li>\r\n");
      out.write("                 <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"nav-main-link-icon fa fa-headset\"></i>Hỗ Trợ</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("    <div class=\"col-3 back-to-top\">\r\n");
      out.write("                  <a id=\"buttonb\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            <ul class=\"list-unstyled CTAs\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"https://www.youtube.com/watch?v=6PebsRhDesA&t=64s\" class=\"download\" target=\"_blank\"><i class=\"nav-main-link-icon fab fa-youtube \" style=\"color: red;\"></i>Video hướng dẫn mua sách trên web</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"SachController\" class=\"article\">Quay lại trang chủ</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <!-- Page Content Holder -->\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-light bg-light conten-nav\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"button\" id=\"sidebarCollapse\" class=\"navbar-btn\">\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"btn btn-dark d-inline-block d-lg-none ml-auto\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                        <i class=\"fas fa-align-justify\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                        <ul class=\"nav navbar-nav ml-auto\">\r\n");
      out.write("                     \r\n");
      out.write("                            \r\n");
      out.write("                         <li class=\"nav-item active\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#\"><i class=\"fas fa-bell nav-main-link-icon\"></i>Thông báo\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                 \t\t\t<li class=\"nav-item\" role=\"presentation\"><a id=\"myycart\" class=\"nav-link active\" href=\"ViewcartController\"><i class=\"fas fa-shopping-cart\"></i> Rỏ Hàng<span class=\"badge badge-light\" id=\"slcart\" style=\"margin-left: 10px;\">");
      out.print(soluong );
      out.write("</span></a></li>\r\n");
      out.write("\r\n");
      out.write("                           \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <!-- Content -->\r\n");
      out.write("            <div class=\"right\" style=\"padding: 2%;\" >\r\n");
      out.write("          \t\t\t <div class=\"block block-rounded block-themed block-fx-pop profile\">\r\n");
      out.write("                    <div class=\"block-header bg-info\">\r\n");
      out.write("                        <div class=\"block-options\">\r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"block-content\">\r\n");
      out.write("                        \r\n");
      out.write("                        <h2 class=\"content-heading\">Thông tin tài khoản</h2>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"offset-2 col-lg-8\">\r\n");
      out.write("                                    <div class=\"form-group row\">\r\n");
      out.write("                                        <label class=\"col-sm-4\">Ngày tạo:</label>\r\n");
      out.write("                                        <div class=\"col-sm-8\">\r\n");
      out.write("                                            <span>2020-08-12 19:28:43</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group row\">\r\n");
      out.write("                                        <label class=\"col-sm-4\">Tài khoản:</label>\r\n");
      out.write("                                        <div class=\"col-sm-8\">\r\n");
      out.write("                                            <span>Trường đẹp trai</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group row\">\r\n");
      out.write("                                        <label class=\"col-sm-4\">Email:</label>\r\n");
      out.write("                                        <div class=\"col-sm-8\">\r\n");
      out.write("                                            <span>anh01663545455@gmail.com</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group row\">\r\n");
      out.write("                                        <label class=\"col-sm-4\">Số dư:</label>\r\n");
      out.write("                                        <div class=\"col-sm-8\">\r\n");
      out.write("                                            <span><strong>0</strong> VNĐ</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group row\">\r\n");
      out.write("                                        <label class=\"col-sm-4\">Đã mua:</label>\r\n");
      out.write("                                        <div class=\"col-sm-8\">\r\n");
      out.write("                                            <span><strong>0</strong> Link</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        <h2 class=\"content-heading\">Đổi mật khẩu</h2>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"offset-2 col-lg-8\">\r\n");
      out.write("                                    <form class=\"mb-5\" action=\"https://muabanfb24h.com/doi-mat-khau\" method=\"POST\">\r\n");
      out.write("                                        <input type=\"hidden\" name=\"_token\" value=\"GcaCQh1727dNSpEjws8mQzGmKeDOwqsdELOK1Hnq\">                                        <div class=\"form-group row\">\r\n");
      out.write("                                            <label class=\"col-sm-4 col-form-label\">Mật khẩu hiện tại</label>\r\n");
      out.write("                                            <div class=\"col-sm-8\">\r\n");
      out.write("                                                <input type=\"password\" class=\"form-control \" name=\"current_password\" placeholder=\"Mật khẩu\">\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group row\">\r\n");
      out.write("                                            <label class=\"col-sm-4 col-form-label\">Mật khẩu mới</label>\r\n");
      out.write("                                            <div class=\"col-sm-8\">\r\n");
      out.write("                                                <input type=\"password\" class=\"form-control \" name=\"password\" placeholder=\"Tạo mật khẩu\">\r\n");
      out.write("                                               </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group row\">\r\n");
      out.write("                                            <label class=\"col-sm-4 col-form-label\">Xác nhận mật khẩu</label>\r\n");
      out.write("                                            <div class=\"col-sm-8\">\r\n");
      out.write("                                                <input type=\"password\" class=\"form-control \" name=\"password_confirmation\" placeholder=\"Xác nhận mật khẩu\">\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group row\">\r\n");
      out.write("                                            <div class=\"col-sm-8 ml-auto\">\r\n");
      out.write("                                                <button type=\"submit\" class=\"btn btn-primary\">Lưu lại</button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t    <script type=\"text/javascript\">\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            $('#sidebarCollapse').on('click', function () {\r\n");
      out.write("                $('#sidebar').toggleClass('active');\r\n");
      out.write("                $(this).toggleClass('active');\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
