/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-09-30 07:06:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Random;
import java.util.Calendar;

public final class soxo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Random");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

//  Calendar n= Calendar.getInstance();//Lay ngay gio tren server 
  //int ngay= n.get(Calendar.DATE);//Lay ngay he thong
  //int thang= n.get(Calendar.MONTH)+1;//0..11
  //int nam= n.get(Calendar.YEAR);

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.ketqua{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-bottom: 1rem;\r\n");
      out.write("    color: #212529;\r\n");
      out.write("    }\r\n");
      out.write("    .result{\r\n");
      out.write("  width: 50%;\r\n");
      out.write("    background: #f1f1f1;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 20%;\r\n");
      out.write("    top: 8%;\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("    .mb-3{\r\n");
      out.write("    width: 200px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"result\">\r\n");
      out.write("<form method=\"post\">\r\n");
      out.write("    <div class=\"input-group mb-3\">\r\n");
      out.write("      <div class=\"input-group-prepend\">\r\n");
      out.write("        <span class=\"input-group-text\">Ngày</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <select name=\"day\" style=\"width: 120px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Ngày</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								for(int i=1;i<=31;i++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option  > ");
      out.print(i );
      out.write(" </option> \r\n");
      out.write("\t\t\t\t\t\t\t\t ");
 }

							 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t</select>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"input-group mb-3\">\r\n");
      out.write("      <div class=\"input-group-append\">\r\n");
      out.write("        <span class=\"input-group-text\">Tháng</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <select name=\"month\" style=\"width: 120px;\">\r\n");
      out.write("\t\t\t\t\t\t\tchọn tháng\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Tháng</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								for(int i=1;i<=12;i++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option  > ");
      out.print(i );
      out.write(" </option> \r\n");
      out.write("\t\t\t\t\t\t\t\t ");
 }

							 
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("    </div>\r\n");
      out.write("       <div class=\"input-group mb-3\">\r\n");
      out.write("      <div class=\"input-group-append\">\r\n");
      out.write("        <span class=\"input-group-text\">Năm</span>\r\n");
      out.write("      </div>\r\n");
      out.write("  <select name=\"year\" style=\"width: 120px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Năm</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								for(int i=2010;i<=2020;i++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option   > ");
      out.print(i );
      out.write(" </option> \r\n");
      out.write("\t\t\t\t\t\t\t\t ");
 }

							 
      out.write("\r\n");
      out.write("\t</select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-primary\" \">Xem Kết Qủa</button>\r\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write("\t\t");

			Calendar cal=Calendar.getInstance();
			if(request.getParameter("a")!=null){
				
      out.write("\r\n");
      out.write("\t\t\t\t<h4 style=\"text-align: center; \">\r\n");
      out.write("\t\t\t\tKết Qủa Xổ Số Ngày \r\n");
      out.write("\t\t\t\t ");
      out.print(request.getParameter("a"));
      out.write("\r\n");
      out.write("\t\t\t\t -");
      out.print(request.getParameter("b"));
      out.write("\r\n");
      out.write("\t\t\t\t -");
      out.print(request.getParameter("c"));
      out.write("\r\n");
      out.write("\t\t\t\t   </h4>\r\n");
      out.write("\t\t\t\t   ");

				   Random rd=new Random();
				   
				   
				   
      out.write("\r\n");
      out.write("\t\t\t\t<table class=\"table ketqua\">\r\n");
      out.write("\t\t\t\t\t  <thead>\r\n");
      out.write("\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t      <th scope=\"col\">Giải</th>\r\n");
      out.write("\t\t\t\t\t      <th scope=\"col\">Kết Qủa Quay Số</th>\r\n");
      out.write("\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t  </thead>\r\n");
      out.write("\t\t\t\t\t  <tbody>\r\n");
      out.write("\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t      <th scope=\"row\" style=\"color: red;\">Đặc Biệt</th>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position: absolute;left: 50%; color: red;\"> ");
      out.print(rd.nextInt(10000) );
      out.write("  </td>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t      <th scope=\"row\">Giải nhất</th>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 50%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t      <th scope=\"row\">Giải nhì</th>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 40%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 60%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t      <th scope=\"row\">Giải ba</th>\r\n");
      out.write("\t\t\t\t\t     <td style=\"position:absolute; left: 32%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t     <td style=\"position:absolute; left: 52%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 72%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t      <th scope=\"row\">Giải bốn</th>\r\n");
      out.write("\t\t\t\t\t    <td style=\"position:absolute; left: 25%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t     <td style=\"position:absolute; left: 42%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 62%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 82%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t      <th scope=\"row\" style=\"position: relative;top: 20px;\">Giải năm</th>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 32%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t     <td style=\"position:absolute; left: 52%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 72%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t    <tr style=\"height: 50px;\">\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 32%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t     <td style=\"position:absolute; left: 52%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 72%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t      <th scope=\"row\">Giải sáu</th>\r\n");
      out.write("\t\t\t\t\t         <td style=\"position:absolute; left: 32%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t     <td style=\"position:absolute; left: 52%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 72%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t      <th scope=\"row\">Giải bảy</th>\r\n");
      out.write("\t\t\t\t\t       <td style=\"position:absolute; left: 25%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t     <td style=\"position:absolute; left: 42%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 62%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t      <td style=\"position:absolute; left: 82%;\">");
      out.print(rd.nextInt(10000) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t  </tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t");
 
			}
		
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
 
		String d=request.getParameter("day");
		String m=request.getParameter("month");
		String y=request.getParameter("year");
		if(d!=null&&y!=null&&m!=null){
			response.sendRedirect("soxo.jsp?a="+d+"&b="+m+"&c="+y);
		}
	
			
	
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- <table width=\"1000\">\r\n");
      out.write("      <tr>\r\n");
      out.write("          <td> \r\n");
      out.write("              <a href=\"soxo.jsp?gt=db\"> Doc bao</a> <hr>\r\n");
      out.write("              <a href=\"soxo.jsp?gt=tt\"> The thao</a> <hr>\r\n");
      out.write("              <a href=\"soxo.jsp?gt=kd\"> kinh doanh</a> <hr>\r\n");
      out.write("           </td>\r\n");
      out.write("          <td> \r\n");
      out.write(" ");

            String ts=request.getParameter("gt");
            if(ts==null)
            	 out.print("Chay lan dau");
            else
            	if(ts.equals("tb"))
            		out.print("Hien thi tt cua trang doc bao");
            	else
            		if(ts.equals("tt"))
                		out.print("Hien thi tt cua trang the thao");
                	else
                		out.print("Trang kinh doanh");
          
      out.write(" </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("   </table> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
