/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-09-22 13:57:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class tailieu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("   \r\n");
      out.write("      <title>Chường đẹp chai</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/tailieu.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  \t<div class=\"main\" id=\"main\">\r\n");
      out.write("  \t\t<div class=\"title\">\r\n");
      out.write("  \t\t\t<span>Đăng Ký</span>\r\n");
      out.write("  \t\t\t<a href=\"#\"><img id=\"close\" src=\"https://tailieu.vn/static/b2013az/templates/version1/default/images/icons/closefanbox.gif\" onclick=close();></a>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t<div class=\"conten\">\r\n");
      out.write("  \t\t\t<p id=\"tl_x\"> &#9830; Đăng nhập nhanh qua Facebook</p>\r\n");
      out.write("  \t\t\t<div class=\"lg-w-fb\">\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("  \t\t\t\t<button class=\"lg\"><img src=\"https://www.hieuhien.vn/wp-content/uploads/2018/12/facebooklite.png\">Login with FaceBook</button>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("  \t\t\t<div class=\"slogan\">\r\n");
      out.write("  \t\t\t\t<p > &diams; hưởng ngay <span class=\"redd\">50</span> ePoints khi đăng ký mới & <span class=\"redd\">5</span> ePoints</p>\r\n");
      out.write("  \t\t\t\t<p style=\"margin-left: 10px;\">cho mỗi lượt chia sẻ Facebook</p>\r\n");
      out.write("  \t\t\t\t<p style=\"cursor: pointer;\">&diams;Tích lũy nhiều ePoints khi Upload tài liệu <span style=\"font-weight: 600;\" class=\"bluee\">>></span>  </p>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("  \t\t\t<a href=\"#\" style=\"text-decoration: none;\"><p id=\"a_regiter\">Đăng ký mới bằng tài khoản TaiLieu.VN</p></a>\r\n");
      out.write("  \t\t\t<p id=\"p_note\">Bạn cần kích hoạt tài khoản qua Email sau khi đăng ký để nhận ngay 50 ePoints thưởng từ TaiLieu.VN</p>\r\n");
      out.write("  \t\t\t<input type=\"text\" name=\"un\" placeholder=\"Nhập Username\" class=\"ip_txt\">\r\n");
      out.write("  \t\t\t<input type=\"text\" name=\"name\" placeholder=\"Nhập Họ và Tên\" class=\"ip_txt\">\r\n");
      out.write("  \t\t\t<div style=\"float: left;\">\r\n");
      out.write("  \t\t\t\t\t<input type=\"text\" name=\"pass\" placeholder=\"Nhập Mật khẩu\" class=\"ip_txt\">\r\n");
      out.write("  \t\t\t<select name=\"gioitinh\" class=\"select ip_txt\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">Giới Tính</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">Nam</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">Nữ</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("  \t\t\t<div>\r\n");
      out.write("\t  \t\t\t<input type=\"text\" name=\"repass\" placeholder=\"Nhập lại mật khẩu\" class=\"ip_txt\">\r\n");
      out.write("\t  \t\t\t<select name=\"birthday\" class=\"select ip_txt\" style=\"width: 80px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Ngày sinh</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

								for(int i=1;i<=31;i++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option > ");
      out.print(i );
      out.write(" </option> \r\n");
      out.write("\t\t\t\t\t\t\t\t ");
 }

							 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<select name=\"month_bd\" class=\"select ip_txt \">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Tháng</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								for(int i=1;i<=12;i++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option > ");
      out.print(i );
      out.write(" </option> \r\n");
      out.write("\t\t\t\t\t\t\t\t ");
 }

							 
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<select name=\"year_bd\" class=\"select ip_txt\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">Năm</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								for(int i=1980;i<=2020;i++){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option > ");
      out.print(i );
      out.write(" </option> \r\n");
      out.write("\t\t\t\t\t\t\t\t ");
 }

							 
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("  \t\t\t<div style=\"float: left;\">\r\n");
      out.write("  \t\t\t\t<input type=\"text\" name=\"email\" placeholder=\"Nhập địa chỉ Email\" class=\"ip_txt\">\r\n");
      out.write("  \t\t\t\t<select name=\"city\"  class=\"select ip_txt\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">Tỉnh/TP</option>\r\n");
      out.write("\t\t\t\t\t\t");

							String tinhthanh[]={"An Giang","Bà Rịa - Vũng Tàu","Bắc Giang","Bắc Kạn",
									"Bạc Liêu",
									"Bắc Ninh",
									"Bến Tre",
									"Bình Định",
									"Bình Dương",
									"Bình Phước",
									"Bình Thuận",
									"Cà Mau",
									"Cao Bằng",
									"Đắk Lắk",
									"Đắk Nông",
									"Điện Biên",
									"Đồng Nai",
									"Đồng Tháp",
									"Gia Lai",
									"Hà Giang",
									"Hà Nam",
									"Hà Tĩnh",
									"Hải Dương",
									"Hậu Giang",
									"Hòa Bình",
									"Hưng Yên",
									"Khánh Hòa",
									"Kiên Giang",
									"Kon Tum",
									"Lai Châu",
									"Lâm Đồng",
									"Lạng Sơn",
									"Lào Cai",
									"Long An",
									"Nam Định",
									"Nghệ An",
									"Ninh Bình",
									"Ninh Thuận",
									"Phú Thọ",
									"Quảng Bình",
									"Quảng Nam",
									"Quảng Ngãi",
									"Quảng Ninh",
									"Quảng Trị",
									"Sóc Trăng",
									"Sơn La",
									"Tây Ninh",
									"Thái Bình",
									"Thái Nguyên",
									"Thanh Hóa",
									"Thừa Thiên Huế",
									"Tiền Giang",
									"Trà Vinh",
									"Tuyên Quang",
									"Vĩnh Long",
									"Vĩnh Phúc",
									"Yên Bái",
									"Phú Yên",	
									"Cần Thơ",
									"Đà Nẵng",
									"Hải Phòng",
									"Hà Nội",
									"TP HCM"};
								for(String i : tinhthanh){
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option > ");
      out.print(i );
      out.write(" </option> \r\n");
      out.write("\t\t\t\t\t\t\t\t ");
 }

							 
      out.write("\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("  \t\t\t<div style=\"float: left;\">\r\n");
      out.write("  \t\t\t\t<input type=\"text\" name=\"reemail\" placeholder=\"Nhập lại địa chỉ Email\" class=\"ip_txt\">\r\n");
      out.write("  \t\t\t\t<input type=\"text\" name=\"code\" placeholder=\"Nhập mã xác nhận\" class=\"ip_txt\" style=\"width: 120px;\">\r\n");
      out.write("  \t\t\t\t<span>12345</span>\r\n");
      out.write("  \t\t\t\t<a href=\"tailieu.php\" style=\"text-decoration: none;font-size: 12px;\">Chọn mã xác nhận khác</a>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t<div class=\"clear\"></div>\r\n");
      out.write("  \t\t<div class=\"check\">\r\n");
      out.write("  \t\t\t<button class=\"creat_acc\" style=\"float: left;\">Đăng Ký</button>\r\n");
      out.write("  \t\t\t<form style=\"float: left;margin-top: 5px;\" action=\"#\">\r\n");
      out.write("  \t\t\t\t<input checked=\"checked\" type=\"checkbox\" name=\"checkb\">\r\n");
      out.write("  \t\t\t\t<span style=\"font-size: 12px;color: #444;font-weight: 400;\">Tôi đồng ý với các Chính Sách và Thỏa Thuận Sử Dụng của TaiLieu.VN</span>\r\n");
      out.write("  \t\t\t</form>\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t\t<div class=\"border_top\"></div>\r\n");
      out.write("  \t\t<span class=\"check2 bluee\">Bạn đã có tài khoản TaiLieu.VN? Đăng nhập</span>\r\n");
      out.write("  \t\t<div class=\"footer\">\r\n");
      out.write("  \t\t\t<div class=\"f-left\">\r\n");
      out.write("  \t\t\t\t<p>Thưởng <span class=\"bluee\">50</span> ePoints khi đăng ký mới</p>\r\n");
      out.write("  \t\t\t\t<p>Tặng <span class=\"bluee\">5</span> ePoints cho mỗi lượt chia sẻ Facebook</p>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("  \t\t\t<div class=\"f-center\">\r\n");
      out.write("  \t\t\t\t<p>Xem và Tải trên <span class=\"bluee\">1 Triệu</span> Tài Liệu miễn phí</p>\r\n");
      out.write("  \t\t\t\t<p>Kết nối <span class=\"bluee\">5 Triệu</span> Thành Viên <a style=\"text-decoration: none;\r\n");
      out.write("    color: #0080AF;\" href=\"https://tailieu.vn/\">TaiLieu.VN</a> </p>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("  \t\t\t<div class=\"f-right\">\r\n");
      out.write("  \t\t\t\t<p>Kết bạn với <a style=\"text-decoration: none;\r\n");
      out.write("    color: #0080AF;font-weight: 600;\" href=\"https://tailieu.vn/\">TaiLieu.VN</a>  trên <a target=\"_blank\" href=\"https://www.facebook.com/tailieu.vn\" style=\"text-decoration: none;\r\n");
      out.write("    color: #0080AF;font-weight: 600;\">TaiLieu.VN</a> </p>\r\n");
      out.write("    <p>để nhận link download miễn phí <span class=\"redd\">100</span></p>\r\n");
      out.write("    <p>tài liệu <span class=\"redd\">HOT</span> mỗi ngày</p>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t<script type=\"text/javascript\">\r\n");
      out.write("  \t\tfunction close(){\r\n");
      out.write("  \t\t\tdocument.getElemenById(\"main\").style.display='none';\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
