/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-09-16 09:16:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class testfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write(" <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Hello word</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container-fluid\" id=\"login-form\">\r\n");
      out.write("\t\t<input type=\"text\" name=\"username\" placeholder=\"Email\">\r\n");
      out.write("\t\t<input type=\"text\" name=\"password\" placeholder=\"MatKhau\">\r\n");
      out.write("\t</div>\r\n");
      out.write("    <table border=\"1\" align=\"center\" cellpadding=\"0\" cellspacing=\"1\"\r\n");
      out.write("    width=\"1000\" style=\"background: green; font-size: 20px;\">\r\n");
      out.write("      <tr>\r\n");
      out.write("          <td> n </td>\r\n");
      out.write("          <td> n^2</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("     ");
for(int i=1;i<=10;i++){ 
      out.write(" \r\n");
      out.write("      <tr>\r\n");
      out.write("          <td> ");
      out.print(i );
      out.write(" </td>\r\n");
      out.write("          <td> ");
      out.print(i*i );
      out.write("</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
} 
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("    <table align=\"center\" width=\"1000\">\r\n");
      out.write("     <tr bgcolor=\"blue\"> <td colspan=\"3\"> Menu ngang </td></tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td bgcolor=\"red\" valign=\"top\">\r\n");
      out.write("         <a href=\"http://docbao.vn\"> doc bao</a>  <hr>\r\n");
      out.write("         <a href=\"bai2.jsp\"> Mo bai 2</a>  <hr>\r\n");
      out.write("         <a href=\"bg.docx\"> Tai bai giang</a>  <hr>\r\n");
      out.write("        </td>\r\n");
      out.write("       <td> <img src=\"bechuc.PNG\" width=\"200\"> </td>\r\n");
      out.write("       <td> <form method=\"post\" action=\"bai2.jsp\">\r\n");
      out.write("              un: <input type=\"text\" name=\"txtun\"> <br>\r\n");
      out.write("              pass: <input type=\"password\" name=\"txtun\"> <br>\r\n");
      out.write("              Chon quoc gia:\r\n");
      out.write("              <select name=\"s1\">\r\n");
      out.write("                <option> Viet Nam</option>\r\n");
      out.write("                <option selected=\"selected\">lao </option>\r\n");
      out.write("                <option> Mien dien</option>\r\n");
      out.write("              </select><br>\r\n");
      out.write("              Tom tat ly lich:\r\n");
      out.write("              <textarea cols=\"80\" rows=\"10\">\r\n");
      out.write("              </textarea>\r\n");
      out.write("      \r\n");
      out.write(" <input type=\"submit\" value=\"Dang ky\"> <br>\r\n");
      out.write("            </form></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
