/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-09-30 09:13:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ums_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("   \r\n");
      out.write("      <title>Chường đẹp chai</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/ums.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <div class=\"m_left\">\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"m_center\">\r\n");
      out.write("            <div class=\"logo\">\r\n");
      out.write("              <img src=\"https://student.husc.edu.vn/Themes/Login/images/Logo-ko-nen.png\" style=\"cursor: pointer;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ums_img\">\r\n");
      out.write("              <img src=\"https://student.husc.edu.vn/Themes/Login/images/image1.png\" style=\"cursor: pointer;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"left_logo\">\r\n");
      out.write("            \t<img alt=\"\" src=\"https://student.husc.edu.vn/Themes/Login/images/logo-small.png\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"m_right\">\r\n");
      out.write("          <form class=\"form_login\" method=\"post\" action=\"ums.jsp\">\r\n");
      out.write("              <span class=\"form_tt\">Sinh viên</span>\r\n");
      out.write("              <div class=\"msv\">\r\n");
      out.write("                <label style=\"margin-bottom: 7px;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-weight: 700;\">Mã sinh viên :</label>\r\n");
      out.write("                <input type=\"text\" name=\"msv\" class=\"myform\" placeholder=\"Mã sinh viên\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"pass\">\r\n");
      out.write("                <label style=\"margin-bottom: 7px;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    display: block;\r\n");
      out.write("    font-weight: 700;\">Mật khẩu :</label>\r\n");
      out.write("                <input type=\"password\" name=\"mk\" class=\"myform\" placeholder=\"Mật khẩu\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <button class=\"btn_lg\" >Đăng nhập</button>\r\n");
      out.write("              <div class=\"err\">\r\n");
      out.write("              ");
      out.write("\r\n");
      out.write(" \t\t\t\t\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t ");

				 	String un=request.getParameter("msv");
				 	if(un!=null){
				 		session.setAttribute("un", un);
				 		response.sendRedirect("t1.jsp");
				 	}
				 
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
