/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-11-19 15:52:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Random;
import bo.Giohangbo;
import bean.loaibean;
import bean.Giohangbean;
import bo.loaibo;
import bean.sachbean;
import java.util.ArrayList;
import bo.sachbo;

public final class viewmycart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bo.loaibo");
    _jspx_imports_classes.add("bo.Giohangbo");
    _jspx_imports_classes.add("bean.loaibean");
    _jspx_imports_classes.add("bo.sachbo");
    _jspx_imports_classes.add("bean.Giohangbean");
    _jspx_imports_classes.add("java.util.Random");
    _jspx_imports_classes.add("bean.sachbean");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("      <title>MinhKhai Búc</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <!-- Import Boostrap css, js, font awesome here -->   \r\n");
      out.write("   <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap JS -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">    \r\n");
      out.write("    <link href=\"./css/home1.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/script.js\"></script>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/home3.css\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"css/minhkhai_style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

		Random rd=new Random();
		ArrayList<sachbean> ds=(ArrayList<sachbean>)request.getAttribute("dssach");
		ArrayList<loaibean> dsloai=(ArrayList<loaibean>)request.getAttribute("dsloai");
		int n=ds.size();
		int m=dsloai.size();
		long soluong=(long)request.getAttribute("soluong");

      out.write("\r\n");
      out.write("<div class=\"header-blue fixed-top\">\r\n");
      out.write("                <nav class=\"navbar navbar-dark navbar-expand-md navigation-clean-search\">\r\n");
      out.write("                <div class=\"container-fluid\"><a class=\"navbar-brand\" href=\"#\">MinhKhaiBook</a><button class=\"navbar-toggler\" data-toggle=\"collapse\" data-target=\"#navcol-1\"><span class=\"sr-only\">Toggle navigation</span><span class=\"navbar-toggler-icon\"></span></button>\r\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navcol-1\">\r\n");
      out.write("                        <ul class=\"nav navbar-nav\">\r\n");
      out.write("                            <li class=\"nav-item\" role=\"presentation\"><a class=\"nav-link active\" href=\"SachController\">Trang Chủ</a></li>\r\n");
      out.write("                            <li class=\"nav-item\" role=\"presentation\"><a class=\"nav-link active\" href=\"#\">Lịch sử mua hàng</a></li>\r\n");
      out.write("                          \r\n");
      out.write("                          \r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                          <div class=\"search_book\">\r\n");
      out.write("                            <form action=\"\">\r\n");
      out.write("                              <input class=\"form-control \" id=\"searchbook\" placeholder=\"Tìm sách\" name=\"txttk\" >\r\n");
      out.write("                            \r\n");
      out.write("                            </form>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        ");
 
                        	if(session.getAttribute("username")!=null){
                        	
                        		
      out.write("\r\n");
      out.write("                        \t\t\r\n");
      out.write("                        \t\t<div class=\"dropdown \">\r\n");
      out.write("                        \t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <button class=\"dropbtn\"><i class=\"fas fa-user user_icon\"></i>Xin Chào ");
      out.print(session.getAttribute("username") );
      out.write("</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <a href=\"profileController\">Profile</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <a href=\"#\">Đơn hàng</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    <a href=\"dangxuatController\">Log Out</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                        \t");
 }else{
                        		
      out.write("\r\n");
      out.write("                        \t\t<form class=\"form-inline mr-auto\" target=\"_self\">\r\n");
      out.write("                            <!-- <div class=\"form-group\"><label for=\"search-field\"><i class=\"fa fa-search\"></i></label><input class=\"form-control search-field\" type=\"search\" name=\"search\" id=\"search-field\"></div> -->\r\n");
      out.write("                        </form><span class=\"navbar-text\"> <a id=\"f-login\" href=\"#\"  class=\"login\">Log In</a></span><a class=\"btn btn-light action-button\" id=\"f-signup\" role=\"button\" href=\"#\">Sign Up</a></div>\r\n");
      out.write("                        \r\n");
      out.write("                       ");
  	}
                       			
                        
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("           \r\n");
      out.write("        </div>\r\n");
      out.write(" <div class=\"wrapper\">\r\n");
      out.write("        <!-- Sidebar Holder -->\r\n");
      out.write("        <nav id=\"sidebar\">\r\n");
      out.write("            <div class=\"sidebar-header\">\r\n");
      out.write("                <h3><a href=\"#\" id=\"mainlogo\">MinhKhai Búc</a></h3>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"list-unstyled components\">\r\n");
      out.write("                <p>Bảng điều khiển</p>\r\n");
      out.write("                <li  class=\"active\"> <a href=\"SachController\" >Trang Chủ</a></li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#homeSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\" class=\"dropdown-toggle\">Danh Mục Sách <span class=\"badge badge-pill badge-danger\"style=\"margin-left: 10px;\">Hot</span></a>\r\n");
      out.write("                    <ul class=\"collapse list-unstyled\" id=\"homeSubmenu\">\r\n");
      out.write("                        ");
 for(int i=0;i<m;i++){  
      out.write("\r\n");
      out.write("\t\t\t\t\t <li>\r\n");
      out.write("\t\t\t\t\t    <a href=\"SachController?type=");
      out.print(dsloai.get(i).getMaloai() );
      out.write('"');
      out.write('>');
      out.print(dsloai.get(i).getTenloai() );
      out.write("<span class=\"badge badge-pill badge-danger\" style=\"margin-left: 10px;\">");
      out.print(rd.nextInt(100));
      out.write("</span></a>\r\n");
      out.write("\t\t\t\t\t  </li>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  ");
} 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"index.php?type=Clone-VN\">Văn phòng phẩm<span class=\"badge badge-pill badge-success\"style=\"margin-left: 10px;\">100</span></a></li>\r\n");
      out.write("\r\n");
      out.write("                <li><a href=\"index.php?type=Clone-US\">Đồ chơi- Thú bông <span class=\"badge badge-pill badge-success\"style=\"margin-left: 10px;\">150 </span></a></li>\r\n");
      out.write("              \t <li>\r\n");
      out.write("               \t\t<a href=\"index.php?type=Clone-EU\">Hàng lưu niệm <span class=\"badge badge-pill badge-success\" style=\"margin-left: 10px;\">134</span>\r\n");
      out.write("              \t\t </a>\r\n");
      out.write("               </li>\r\n");
      out.write("                 <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"nav-main-link-icon fa fa-headset\"></i>Hỗ Trợ</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("    <div class=\"col-3 back-to-top\">\r\n");
      out.write("                  <a id=\"buttonb\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            <ul class=\"list-unstyled CTAs\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"https://www.youtube.com/watch?v=6PebsRhDesA&t=64s\" class=\"download\" target=\"_blank\"><i class=\"nav-main-link-icon fab fa-youtube \" style=\"color: red;\"></i>Video hướng dẫn mua acc</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"SachController\" class=\"article\">Quay lại trang chủ</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <!-- Page Content Holder -->\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-light bg-light conten-nav\">\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"button\" id=\"sidebarCollapse\" class=\"navbar-btn\">\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                        <span></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button class=\"btn btn-dark d-inline-block d-lg-none ml-auto\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                        <i class=\"fas fa-align-justify\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                        <ul class=\"nav navbar-nav ml-auto\">\r\n");
      out.write("                     \r\n");
      out.write("                            \r\n");
      out.write("                         <li class=\"nav-item active\">\r\n");
      out.write("                                <a class=\"nav-link\" href=\"#\"><i class=\"fas fa-bell nav-main-link-icon\"></i>Thông báo\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                 \t\t\t<li class=\"nav-item\" role=\"presentation\"><a id=\"myycart\" class=\"nav-link active\" href=\"ViewcartController\"><i class=\"fas fa-shopping-cart\"></i> Rỏ Hàng<span class=\"badge badge-light\" id=\"slcart\" style=\"margin-left: 10px;\">");
      out.print(soluong );
      out.write("</span></a></li>\r\n");
      out.write("\r\n");
      out.write("                           \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <!-- Content -->\r\n");
      out.write("\t\t\t<div class=\"mycart\">\r\n");
      out.write("\t\t\t\t");

	
		Giohangbo gh=(Giohangbo)session.getAttribute("GioHang");
		if(gh==null){
			
		}
		if(gh!=null){int i=1; 
      out.write("\r\n");
      out.write("\t\t\t\t<table class=\"table table-bordered\" id=\"giohang\">\r\n");
      out.write("\t\t\t  <thead>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <th scope=\"col\">STT</th>\r\n");
      out.write("\t\t\t      <th scope=\"col\">Tên sách</th>\r\n");
      out.write("\t\t\t      <th scope=\"col\">Mã sách sách</th>\r\n");
      out.write("\t\t\t       <th scope=\"col\">Hình ảnh</th>\r\n");
      out.write("\t\t\t      <th scope=\"col\">Số Lượng</th>\r\n");
      out.write("\t\t\t      <th scope=\"col\">Giá Bán</th>\r\n");
      out.write("\t\t\t      <th scope=\"col\">Thao tác</th>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t  </thead>\r\n");
      out.write("\t\t");
 	for(Giohangbean g:gh.ds){
				
				
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<tbody >\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td id=\"stt\">");
      out.print(i );
      out.write("</td>\r\n");
      out.write("\t\t\t      <td>");
      out.print(g.getTensach() );
      out.write("</td>\r\n");
      out.write("\t\t\t      <td id=\"masach");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(g.getMasach().trim());
      out.write("</td>\r\n");
      out.write("\t\t\t       <td> <img src=\"");
      out.print(g.getAnh() );
      out.write("\" ></td>\r\n");
      out.write("\t\t\t      <td><div class=\"number_input\">\r\n");
      out.write("\t\t\t      \t<span class=\"tru\" id=\"number_down\" onclick=\"tru");
      out.print(i);
      out.write("()\">-</span>\r\n");
      out.write("\t\t\t      \t<input type=\"tel\" class=\"soluong_input\" id=\"soluong");
      out.print(i );
      out.write("\" value=\"");
      out.print((int)g.getSoluong());
      out.write("\">\r\n");
      out.write("\t\t\t      \t<span class=\"cong\" id=\"number_up\" onclick=\"cong");
      out.print(i);
      out.write("()\">+</span></div></td>\r\n");
      out.write("\t\t\t      <td>");
      out.print((long)g.getGiaban()+" đ");
      out.write("</td>\r\n");
      out.write("\t\t\t     ");
      out.write("\r\n");
      out.write("\t\t\t      <td> <button class=\"delete btn btn-outline-danger\" id=\"del_");
      out.print(g.getMasach());
      out.write("\">Xóa</button></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\tfunction cong");
      out.print(i);
      out.write("()\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t    var value =parseInt(document.getElementById('soluong");
      out.print(i);
      out.write("').value);\r\n");
      out.write("\t\t\t\t\t    value = isNaN(value) ? 0 : value;\r\n");
      out.write("\t\t\t\t\t    value++;\r\n");
      out.write("\t\t\t\t\t    document.getElementById('soluong");
      out.print(i);
      out.write("').value = value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tfunction tru");
      out.print(i);
      out.write("()\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t    var value = parseInt(document.getElementById('soluong");
      out.print(i);
      out.write("').value);\r\n");
      out.write("\t\t\t\t\t    value = isNaN(value) ? 0 : value;\r\n");
      out.write("\t\t\t\t\t    value--;\r\n");
      out.write("\t\t\t\t\t    if(value==0){\r\n");
      out.write("\t\t\t\t\t    \tdocument.getElementById('number_down').attr(\"disabled\", true);\r\n");
      out.write("\t\t\t\t\t    }\r\n");
      out.write("\t\t\t\t\t    document.getElementById('soluong");
      out.print(i);
      out.write("').value = value;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t  $(document).ready(function(){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t // tăng số lượng \r\n");
      out.write("\t\t\t\t\t $('.cong').click(function(){\r\n");
      out.write("\t\t\t\t\t   var slm=parseInt(document.getElementById('soluong");
      out.print(i);
      out.write("').value);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t   //  id\r\n");
      out.write("\t\t\t\t\t   var deleteid = '");
      out.print(g.getMasach().trim() );
      out.write("';\r\n");
      out.write("\t\t\t\t\t   // AJAX Request\r\n");
      out.write("\t\t\t\t\t   $.ajax({\r\n");
      out.write("\t\t\t\t\t     url: 'editController',\r\n");
      out.write("\t\t\t\t\t     type: 'GET',\r\n");
      out.write("\t\t\t\t\t     data: { id:deleteid,\r\n");
      out.write("\t\t\t\t\t    \t \tslm:slm},\r\n");
      out.write("\t\t\t\t\t     sussess:function(response){\r\n");
      out.write("\t\t\t\t\t       if(response==1){\r\n");
      out.write("\t\t\t\t\t    \t   //alert(\"Tăng số lượng thành công\");\t\t\t    \t   \r\n");
      out.write("\t\t\t\t\t    \t   return;\r\n");
      out.write("\t\t\t\t\t      }else{\r\n");
      out.write("\t\t\t\t\t    alert(response);\r\n");
      out.write("\t\t\t\t\t    alert(\"Lỗi\");\r\n");
      out.write("\t\t\t\t\t      }\r\n");
      out.write("\t\t\t\t\t       }\r\n");
      out.write("\t\t\t\t\t   });\r\n");
      out.write("\t\t\t\t\t });\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t \t\t</tbody>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t");
	
		i++;
		}
		}
		
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t\t.loading{\r\n");
      out.write("\t\t  position: absolute;\r\n");
      out.write("\t\t\t  left: 50%;\r\n");
      out.write("\t\t\t  top: 50%;\r\n");
      out.write("\t\t\tdisplay: none;\r\n");
      out.write("\t\t\twidth: 220px;\r\n");
      out.write("\t\t\theight: 60px;\r\n");
      out.write("\t\t\tborder: 2px solid #0fc32a;\r\n");
      out.write("\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\tfont-size: 20px;\r\n");
      out.write("\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\ttext-transform: uppercase;\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\tline-height: 56px;\r\n");
      out.write("\t\t\tbox-sizing: border-box;\r\n");
      out.write("\t\t\tborder-radius: 50px;\r\n");
      out.write("\t\t\tbackground-color: transparent;\r\n");
      out.write("\t\t\toutline: none;\r\n");
      out.write("\t\t\ttransition: all ease 0.5s;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.btn-active{\r\n");
      out.write("\t\t\tfont-size: 0;\r\n");
      out.write("\t\t\twidth: 200px;\r\n");
      out.write("\t\t\theight: 200px;\r\n");
      out.write("\t\t\tborder-radius: 50%;\r\n");
      out.write("\t\t\tborder-left-color: transparent;\r\n");
      out.write("\t\t\tanimation: rotate 1.4s ease 0.5s infinite;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t@keyframes rotate{\r\n");
      out.write("\t\t\t0%{\r\n");
      out.write("\t\t\t\ttransform: rotate(360deg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t.success{\r\n");
      out.write("\t\t\tposition: relative;\r\n");
      out.write("\t\t\tbackground-color: #fff;\r\n");
      out.write("\t\t\tanimation: bounce .3s ease-in;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t@keyframes bounce{\r\n");
      out.write("\t\t\t0%{\r\n");
      out.write("\t\t\t\ttransform: scale(0.9);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.success:before{\r\n");
      out.write("\t\t\tcontent: '';\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tbackground: url(./img/check-solid.svg) no-repeat; /* Check Solid is fontawesome icon */\r\n");
      out.write("\t\t\tleft: 0;\r\n");
      out.write("\t\t\tright: 0;\r\n");
      out.write("\t\t\tmargin: 0 auto;\r\n");
      out.write("\t\t\twidth: 31px;\r\n");
      out.write("\t\t\theight: 31px;\r\n");
      out.write("\t\t\tline-height: 31px;\r\n");
      out.write("\t\t\ttop: 8px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style> \r\n");
      out.write("\t<button class=\"loading\" id=\"load\">Button</button>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\".cong\").click(function(){\r\n");
      out.write("\t\tdocument.getElementById('giohang').style.opacity = \"0.09\";\r\n");
      out.write("\t\tdocument.getElementById('load').style.display = \"block\";\r\n");
      out.write("\t\t$(\".loading\").addClass(\"btn-active\");\r\n");
      out.write("\t\t// Add Success Class After 3.7 Seconds\r\n");
      out.write("\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t$(\".loading\").addClass(\"success\");\r\n");
      out.write("\t\t\tdocument.getElementById('load').style.display = \"none\";\r\n");
      out.write("\t\t\tdocument.getElementById('giohang').style.opacity = \"1\";\r\n");
      out.write("\t\t}, 1000);\r\n");
      out.write("\r\n");
      out.write("\t\t// Remove class after 5 second\r\n");
      out.write("\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t$(\".loading\").removeClass(\"btn-active\");\r\n");
      out.write("\t\t\t$(\".loading\").removeClass(\"success\");\r\n");
      out.write("\t\t}, 1000);\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write(" // Delete \r\n");
      out.write(" $('.delete').click(function(){\r\n");
      out.write("\t//var sl=$(\"slcart\").html();\r\n");
      out.write("\t\r\n");
      out.write("  if( confirm('Bạn Có Muốn Xóa Dữ liệu Không')){\r\n");
      out.write("   var el = this;\r\n");
      out.write("   var id = this.id;\r\n");
      out.write("   var splitid = id.split(\"_\");\r\n");
      out.write("   // Delete id\r\n");
      out.write("   var deleteid = splitid[1];\r\n");
      out.write("   // AJAX Request\r\n");
      out.write("   $.ajax({\r\n");
      out.write("     url: 'deleteController',\r\n");
      out.write("     type: 'GET',\r\n");
      out.write("     data: { id:deleteid },\r\n");
      out.write("     success:function(response){\r\n");
      out.write("       if(response ==1){\r\n");
      out.write(" \t\t  $(el).closest('tr').css('background','tomato');\r\n");
      out.write("\t\t   $(el).closest('tr').fadeOut(800,function(){\r\n");
      out.write("\t\t      $(this).remove();\r\n");
      out.write("\t\t   });\r\n");
      out.write("\t\t   document.getElementById('slcart').innerHTML = $(\"#slcart\").html()-1;\r\n");
      out.write("      }else{\r\n");
      out.write("    alert('Invalid ID.');\r\n");
      out.write("    alert(response);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("   });\r\n");
      out.write("}\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModalCenter\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalCenterTitle\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLongTitle\">Thông Báo</h5>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("          <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\" id=\"my_modal\">\r\n");
      out.write("       \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <a type=\"button\" class=\"btn btn-outline-primary\" data-dismiss=\"modal\">Tiếp Tục Mua Sách</a>\r\n");
      out.write("      <!--   <a href=\"index.jsp\" type=\"button\" class=\"btn btn-outline-primary\">Tiếp Tục Mua Sách</a> -->\r\n");
      out.write("   \t\t<a href=\"viewcart.jsp\" type=\"button\" class=\"btn btn-outline-success\">Xem giỏ hàng</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            $('#sidebarCollapse').on('click', function () {\r\n");
      out.write("                $('#sidebar').toggleClass('active');\r\n");
      out.write("                $(this).toggleClass('active');\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    \t<script>\r\n");
      out.write("\t\t\t\t\t/* $(\".delete\").click(function(){\r\n");
      out.write("\t\t\t\t\t\t if( confirm('Bạn Có Muốn Xóa Dữ liệu Không')){\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('slcart').innerHTML = $(\"#slcart\").html()-1;}\r\n");
      out.write("\t\t\t\t\t}) */\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
